import { Red_Hat_Display as redHatDisplay } from 'next/font/google'
import './globals.css'

const redHat = redHatDisplay({
  subsets: ['latin'],
  variable: '--font-red-hat',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${redHat.variable} xs:bg-desktop flex h-screen flex-col items-center justify-center bg-pale-blue bg-mobile bg-contain bg-no-repeat font-red-hat`}
      >
        {children}
      </body>
    </html>
  )
}
